name: custom_lint_rules
description: "Lint rules customizados para Cadife Smart Travel"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.11.4

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.7.0
