apiVersion: v1
kind: Service
metadata:
  name: cadife-backend-svc
  labels:
    app: cadife-backend
spec:
  type: ClusterIP # Serviço interno, exposto externamente apenas via Ingress/Gateway
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: cadife-backend
