apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace sugerido para o ambiente (deve existir previamente no cluster)
namespace: cadife-prod

resources:
  - backend-configmap.yaml
  - backend-secret.example.yaml
  - backend-deployment.yaml
  - backend-service.yaml
