"""create_suitcase_tables

Revision ID: 313501e5eb7a
Revises: e8f9a0b1c2d3
Create Date: 2026-05-08 16:31:00.335328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '313501e5eb7a'
down_revision: Union[str, None] = 'e8f9a0b1c2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suitcase_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_destino', postgresql.ENUM('praia', 'frio', 'urbano', 'aventura', name='destination_type_enum'), nullable=False),
    sa.Column('categoria', postgresql.ENUM('documentos', 'roupas', 'higiene', 'eletrônicos', 'saúde', 'acessórios', 'outros', name='suitcase_category_enum'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('quantidade_sugerida', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suitcase_suggestions_tipo_destino'), 'suitcase_suggestions', ['tipo_destino'], unique=False)
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('original_payload', sa.JSON(), nullable=False),
    sa.Column('error_trace', sa.Text(), nullable=False),
    sa.Column('retry_count_exhausted', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_queue_lead_id'), 'dead_letter_queue', ['lead_id'], unique=False)
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_queue_lead_id'), 'notification_queue', ['lead_id'], unique=False)
    op.create_index(op.f('ix_notification_queue_next_retry_at'), 'notification_queue', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_notification_queue_processing_started_at'), 'notification_queue', ['processing_started_at'], unique=False)
    op.create_index(op.f('ix_notification_queue_status'), 'notification_queue', ['status'], unique=False)
    op.create_table('suitcase_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('categoria', postgresql.ENUM('documentos', 'roupas', 'higiene', 'eletrônicos', 'saúde', 'acessórios', 'outros', name='suitcase_category_enum'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('empacotado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suitcase_items_lead_id'), 'suitcase_items', ['lead_id'], unique=False)
    op.create_index(op.f('ix_suitcase_items_user_id'), 'suitcase_items', ['user_id'], unique=False)
    op.drop_index('ix_documentos_deleted_at', table_name='documentos')
    op.drop_index('ix_documentos_lead_id', table_name='documentos')
    op.drop_table('documentos')
    op.alter_column('agendamentos', 'status',
               existing_type=postgresql.ENUM('pendente', 'confirmado', 'realizado', 'cancelado', name='agendamento_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agendamentos', 'tipo',
               existing_type=postgresql.ENUM('online', 'presencial', name='agendamento_tipo_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('briefings', 'completude_pct',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('briefings_lead_id_key', 'briefings', type_='unique')
    op.alter_column('interacoes', 'tipo_mensagem',
               existing_type=postgresql.ENUM('texto', 'audio', 'imagem', 'documento', name='tipo_mensagem_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leads', 'origem',
               existing_type=postgresql.ENUM('whatsapp', 'app', 'web', name='lead_origem_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leads', 'status',
               existing_type=postgresql.ENUM('novo', 'em_atendimento', 'qualificado', 'agendado', 'proposta', 'fechado', 'perdido', name='lead_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leads', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('leads_telefone_key', 'leads', type_='unique')
    op.drop_index('ix_leads_telefone_hash', table_name='leads')
    op.create_index(op.f('ix_leads_telefone_hash'), 'leads', ['telefone_hash'], unique=False)
    op.alter_column('propostas', 'status',
               existing_type=postgresql.ENUM('rascunho', 'enviada', 'aprovada', 'recusada', 'em_revisao', 'expirada', name='proposta_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('propostas', 'status',
               existing_type=postgresql.ENUM('rascunho', 'enviada', 'aprovada', 'recusada', 'em_revisao', 'expirada', name='proposta_status_enum'),
               server_default=sa.text("'rascunho'::proposta_status_enum"),
               existing_nullable=False)
    op.drop_index(op.f('ix_leads_telefone_hash'), table_name='leads')
    op.create_index('ix_leads_telefone_hash', 'leads', ['telefone_hash'], unique=True)
    op.create_unique_constraint('leads_telefone_key', 'leads', ['telefone'])
    op.alter_column('leads', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('leads', 'status',
               existing_type=postgresql.ENUM('novo', 'em_atendimento', 'qualificado', 'agendado', 'proposta', 'fechado', 'perdido', name='lead_status_enum'),
               server_default=sa.text("'novo'::lead_status_enum"),
               existing_nullable=False)
    op.alter_column('leads', 'origem',
               existing_type=postgresql.ENUM('whatsapp', 'app', 'web', name='lead_origem_enum'),
               server_default=sa.text("'whatsapp'::lead_origem_enum"),
               existing_nullable=False)
    op.alter_column('interacoes', 'tipo_mensagem',
               existing_type=postgresql.ENUM('texto', 'audio', 'imagem', 'documento', name='tipo_mensagem_enum'),
               server_default=sa.text("'texto'::tipo_mensagem_enum"),
               existing_nullable=False)
    op.create_unique_constraint('briefings_lead_id_key', 'briefings', ['lead_id'])
    op.alter_column('briefings', 'completude_pct',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agendamentos', 'tipo',
               existing_type=postgresql.ENUM('online', 'presencial', name='agendamento_tipo_enum'),
               server_default=sa.text("'online'::agendamento_tipo_enum"),
               existing_nullable=False)
    op.alter_column('agendamentos', 'status',
               existing_type=postgresql.ENUM('pendente', 'confirmado', 'realizado', 'cancelado', name='agendamento_status_enum'),
               server_default=sa.text("'pendente'::agendamento_status_enum"),
               existing_nullable=False)
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('categoria', postgresql.ENUM('passagem', 'voucher', 'transfer', 'seguro', 'itinerario', 'outros', name='documento_categoria_enum'), autoincrement=False, nullable=False),
    sa.Column('tamanho_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('enviado_por', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['enviado_por'], ['users.id'], name='documentos_enviado_por_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='documentos_lead_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='documentos_pkey')
    )
    op.create_index('ix_documentos_lead_id', 'documentos', ['lead_id'], unique=False)
    op.create_index('ix_documentos_deleted_at', 'documentos', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_suitcase_items_user_id'), table_name='suitcase_items')
    op.drop_index(op.f('ix_suitcase_items_lead_id'), table_name='suitcase_items')
    op.drop_table('suitcase_items')
    op.drop_index(op.f('ix_notification_queue_status'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_processing_started_at'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_next_retry_at'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_lead_id'), table_name='notification_queue')
    op.drop_table('notification_queue')
    op.drop_index(op.f('ix_dead_letter_queue_lead_id'), table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    op.drop_index(op.f('ix_suitcase_suggestions_tipo_destino'), table_name='suitcase_suggestions')
    op.drop_table('suitcase_suggestions')
    # ### end Alembic commands ###
