"""add_profile_preferences_to_users

Revision ID: 63a1b837b445
Revises: dd4f06e3dc70
Create Date: 2026-04-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63a1b837b445'
down_revision: Union[str, None] = 'dd4f06e3dc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('tipo_viagem', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('preferencias', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('tem_passaporte', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tem_passaporte')
    op.drop_column('users', 'preferencias')
    op.drop_column('users', 'tipo_viagem')
    op.drop_column('users', 'telefone')
    # ### end Alembic commands ###
