"""create travel_diary_entries table

Revision ID: 67b69bf11b14
Revises: f547e5dee9bf
Create Date: 2026-05-09 20:32:17.625207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b69bf11b14'
down_revision: Union[str, None] = 'f547e5dee9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.Column('enviado_por', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enviado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_deleted_at'), 'documentos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documentos_lead_id'), 'documentos', ['lead_id'], unique=False)
    op.create_table('travel_diary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('foto_url', sa.String(length=1024), nullable=False),
    sa.Column('thumb_url', sa.String(length=1024), nullable=False),
    sa.Column('nota', sa.String(length=280), nullable=True),
    sa.Column('data_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_diary_entries_lead_id'), 'travel_diary_entries', ['lead_id'], unique=False)
    op.create_index(op.f('ix_travel_diary_entries_user_id'), 'travel_diary_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_diary_entries_user_id'), table_name='travel_diary_entries')
    op.drop_index(op.f('ix_travel_diary_entries_lead_id'), table_name='travel_diary_entries')
    op.drop_table('travel_diary_entries')
    op.drop_index(op.f('ix_documentos_lead_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_deleted_at'), table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
