"""create_audit_logs_table

Revision ID: 693168e8c4e0
Revises: c79f9278911e
Create Date: 2026-05-14 16:27:37.969714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '693168e8c4e0'
down_revision: Union[str, None] = 'c79f9278911e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_templates_active'), table_name='message_templates', postgresql_where='(deletado_em IS NULL)')
    op.drop_table('message_templates')
    op.drop_table('agency_settings')
    op.drop_index(op.f('ix_travel_checkpoints_lead_id'), table_name='travel_checkpoints')
    op.drop_table('travel_checkpoints')
    op.alter_column('conversation_summaries', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_summaries', 'resumo_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('conversation_summaries', 'resumo_pendente',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_conversation_summaries_lead_id'), 'conversation_summaries', ['lead_id'], unique=False)
    op.alter_column('proposta_versoes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('proposta_versoes', 'snapshot_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('idx_propostas_active'), table_name='propostas', postgresql_where='(deletado_em IS NULL)')
    op.alter_column('sale_goals', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_goals', 'target',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_goals', 'achieved',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('sale_goals', 'achieved',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sale_goals', 'target',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sale_goals', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_propostas_active'), 'propostas', ['lead_id', 'status'], unique=False, postgresql_where='(deletado_em IS NULL)')
    op.alter_column('proposta_versoes', 'snapshot_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('proposta_versoes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_summaries_lead_id'), table_name='conversation_summaries')
    op.alter_column('conversation_summaries', 'resumo_pendente',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversation_summaries', 'resumo_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('conversation_summaries', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('travel_checkpoints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('checkpoint', postgresql.ENUM('BRIEFING_COLETADO', 'CURADORIA_INICIADA', 'PROPOSTA_ENVIADA', 'PROPOSTA_APROVADA', 'VIAGEM_CONFIRMADA', 'VIAGEM_EM_ANDAMENTO', 'VIAGEM_CONCLUIDA', name='travel_checkpoint_enum'), autoincrement=False, nullable=False),
    sa.Column('ativado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ativado_por', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('travel_checkpoints_lead_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('travel_checkpoints_pkey')),
    sa.UniqueConstraint('lead_id', 'checkpoint', name=op.f('uq_travel_checkpoints_lead_checkpoint'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_travel_checkpoints_lead_id'), 'travel_checkpoints', ['lead_id'], unique=False)
    op.create_table('agency_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('agency_id', sa.UUID(), server_default=sa.text("'00000000-0000-0000-0000-000000000001'::uuid"), autoincrement=False, nullable=False),
    sa.Column('horario_funcionamento', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"fim": "16:00", "dias": [1, 2, 3, 4, 5], "inicio": "09:00"}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('notificacoes_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"novos_leads": true, "leads_qualificados": true, "propostas_aprovadas": true, "agendamentos_confirmados": true}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('agency_settings_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('agency_settings_pkey')),
    sa.UniqueConstraint('agency_id', name=op.f('uq_agency_settings_agency'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('message_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('agency_id', sa.UUID(), server_default=sa.text("'00000000-0000-0000-0000-000000000001'::uuid"), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('conteudo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('variaveis', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deletado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("categoria::text = ANY (ARRAY['boas_vindas'::character varying, 'lembrete'::character varying, 'pos_curadoria'::character varying, 'follow_up'::character varying, 'proposta'::character varying, 'outro'::character varying]::text[])", name=op.f('ck_template_categoria')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('message_templates_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_templates_pkey'))
    )
    op.create_index(op.f('idx_templates_active'), 'message_templates', ['agency_id', 'categoria'], unique=False, postgresql_where='(deletado_em IS NULL)')
    # ### end Alembic commands ###
