"""sync_auth_and_bio_fields

Revision ID: 81aa4aeb2950
Revises: b881cb32ff51
Create Date: 2026-05-14 13:08:30.018868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81aa4aeb2950'
down_revision: Union[str, None] = 'b881cb32ff51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=1024), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True)
    op.create_table('travels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travels_status'), 'travels', ['status'], unique=False)
    op.create_index(op.f('ix_travels_user_id'), 'travels', ['user_id'], unique=False)
    op.create_table('lead_score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('score_numerico', sa.Integer(), nullable=False),
    sa.Column('score_label', sa.String(length=10), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('criterios_json', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_score_history_lead_id'), 'lead_score_history', ['lead_id'], unique=False)
    op.alter_column('agendamentos', 'status',
               existing_type=postgresql.ENUM('pendente', 'confirmado', 'realizado', 'cancelado', name='agendamento_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agendamentos', 'tipo',
               existing_type=postgresql.ENUM('online', 'presencial', name='agendamento_tipo_enum'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_aya_toggle_history_lead_id_alterado_em'), table_name='aya_toggle_history')
    op.alter_column('briefings', 'completude_pct',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('briefings_lead_id_key'), 'briefings', type_='unique')
    op.add_column('documentos', sa.Column('travel_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_documentos_travel_id'), 'documentos', ['travel_id'], unique=False)
    op.create_foreign_key(None, 'documentos', 'travels', ['travel_id'], ['id'], ondelete='SET NULL')
    op.alter_column('interacoes', 'tipo_mensagem',
               existing_type=postgresql.ENUM('texto', 'audio', 'imagem', 'documento', name='tipo_mensagem_enum'),
               server_default=None,
               existing_nullable=False)
    op.add_column('leads', sa.Column('score_numerico', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('score_calculado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('client_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('offer_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('leads', sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('leads', 'origem',
               existing_type=postgresql.ENUM('whatsapp', 'app', 'web', 'indicação', 'telefone', 'presencial', 'rede social', 'outro', 'manual', name='lead_origem_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leads', 'status',
               existing_type=postgresql.ENUM('novo', 'em_atendimento', 'qualificado', 'agendado', 'proposta', 'fechado', 'perdido', name='lead_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leads', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('leads_telefone_key'), 'leads', type_='unique')
    op.drop_index(op.f('ix_leads_telefone_hash'), table_name='leads')
    op.create_index(op.f('ix_leads_telefone_hash'), 'leads', ['telefone_hash'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'offers', ['offer_id'], ['id'], ondelete='SET NULL')
    op.add_column('offers', sa.Column('agency_id', sa.UUID(), nullable=False))
    op.add_column('offers', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('offers', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('offers', sa.Column('destination', sa.String(length=255), nullable=False))
    op.add_column('offers', sa.Column('destination_image_url', sa.String(length=500), nullable=True))
    op.add_column('offers', sa.Column('departure_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('offers', sa.Column('return_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('offers', sa.Column('booking_deadline', sa.DateTime(timezone=True), nullable=False))
    op.add_column('offers', sa.Column('duration_days', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('accommodations', sa.JSON(), nullable=False))
    op.add_column('offers', sa.Column('included_services', sa.JSON(), nullable=False))
    op.add_column('offers', sa.Column('travelers', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('available_spots', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('spots_reserved', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('offers', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('offers', sa.Column('discounts', sa.JSON(), nullable=True))
    op.add_column('offers', sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('offers', sa.Column('highlights', sa.JSON(), nullable=False))
    op.add_column('offers', sa.Column('amenities', sa.JSON(), nullable=False))
    op.add_column('offers', sa.Column('views', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('interests', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('conversions', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('offers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('offers', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_offers_agency_id'), 'offers', ['agency_id'], unique=False)
    op.create_index(op.f('ix_offers_booking_deadline'), 'offers', ['booking_deadline'], unique=False)
    op.create_index(op.f('ix_offers_departure_date'), 'offers', ['departure_date'], unique=False)
    op.create_index(op.f('ix_offers_destination'), 'offers', ['destination'], unique=False)
    op.create_index(op.f('ix_offers_published_at'), 'offers', ['published_at'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_title'), 'offers', ['title'], unique=False)
    op.drop_constraint(op.f('offers_criado_por_fkey'), 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'users', ['agency_id'], ['id'])
    op.drop_column('offers', 'categoria')
    op.drop_column('offers', 'preco_base')
    op.drop_column('offers', 'descricao')
    op.drop_column('offers', 'data_saida_sugerida')
    op.drop_column('offers', 'titulo')
    op.drop_column('offers', 'atualizado_em')
    op.drop_column('offers', 'servicos_inclusos')
    op.drop_column('offers', 'destino')
    op.drop_column('offers', 'duracao_dias')
    op.drop_column('offers', 'criado_em')
    op.drop_column('offers', 'imagens')
    op.drop_column('offers', 'criado_por')
    op.alter_column('propostas', 'status',
               existing_type=postgresql.ENUM('rascunho', 'enviada', 'aprovada', 'recusada', 'em_revisao', 'expirada', name='proposta_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('global_logout_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('users', 'global_logout_at')
    op.drop_column('users', 'bio')
    op.alter_column('propostas', 'status',
               existing_type=postgresql.ENUM('rascunho', 'enviada', 'aprovada', 'recusada', 'em_revisao', 'expirada', name='proposta_status_enum'),
               server_default=sa.text("'rascunho'::proposta_status_enum"),
               existing_nullable=False)
    op.add_column('offers', sa.Column('criado_por', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('imagens', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('duracao_dias', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('destino', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('servicos_inclusos', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('data_saida_sugerida', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('preco_base', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('categoria', postgresql.ENUM('internacional', 'nacional', 'lua_de_mel', 'família', 'aventura', 'cruzeiro', 'executivo', 'outros', name='offer_categoria_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key(op.f('offers_criado_por_fkey'), 'offers', 'users', ['criado_por'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_offers_title'), table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_published_at'), table_name='offers')
    op.drop_index(op.f('ix_offers_destination'), table_name='offers')
    op.drop_index(op.f('ix_offers_departure_date'), table_name='offers')
    op.drop_index(op.f('ix_offers_booking_deadline'), table_name='offers')
    op.drop_index(op.f('ix_offers_agency_id'), table_name='offers')
    op.drop_column('offers', 'published_at')
    op.drop_column('offers', 'updated_at')
    op.drop_column('offers', 'created_at')
    op.drop_column('offers', 'conversions')
    op.drop_column('offers', 'interests')
    op.drop_column('offers', 'views')
    op.drop_column('offers', 'amenities')
    op.drop_column('offers', 'highlights')
    op.drop_column('offers', 'final_price')
    op.drop_column('offers', 'discounts')
    op.drop_column('offers', 'currency')
    op.drop_column('offers', 'base_price')
    op.drop_column('offers', 'spots_reserved')
    op.drop_column('offers', 'available_spots')
    op.drop_column('offers', 'travelers')
    op.drop_column('offers', 'included_services')
    op.drop_column('offers', 'accommodations')
    op.drop_column('offers', 'duration_days')
    op.drop_column('offers', 'booking_deadline')
    op.drop_column('offers', 'return_date')
    op.drop_column('offers', 'departure_date')
    op.drop_column('offers', 'destination_image_url')
    op.drop_column('offers', 'destination')
    op.drop_column('offers', 'description')
    op.drop_column('offers', 'title')
    op.drop_column('offers', 'agency_id')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_telefone_hash'), table_name='leads')
    op.create_index(op.f('ix_leads_telefone_hash'), 'leads', ['telefone_hash'], unique=True)
    op.create_unique_constraint(op.f('leads_telefone_key'), 'leads', ['telefone'], postgresql_nulls_not_distinct=False)
    op.alter_column('leads', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('leads', 'status',
               existing_type=postgresql.ENUM('novo', 'em_atendimento', 'qualificado', 'agendado', 'proposta', 'fechado', 'perdido', name='lead_status_enum'),
               server_default=sa.text("'novo'::lead_status_enum"),
               existing_nullable=False)
    op.alter_column('leads', 'origem',
               existing_type=postgresql.ENUM('whatsapp', 'app', 'web', 'indicação', 'telefone', 'presencial', 'rede social', 'outro', 'manual', name='lead_origem_enum'),
               server_default=sa.text("'whatsapp'::lead_origem_enum"),
               existing_nullable=False)
    op.drop_column('leads', 'deletado_em')
    op.drop_column('leads', 'budget')
    op.drop_column('leads', 'offer_id')
    op.drop_column('leads', 'client_id')
    op.drop_column('leads', 'score_calculado_em')
    op.drop_column('leads', 'score_numerico')
    op.alter_column('interacoes', 'tipo_mensagem',
               existing_type=postgresql.ENUM('texto', 'audio', 'imagem', 'documento', name='tipo_mensagem_enum'),
               server_default=sa.text("'texto'::tipo_mensagem_enum"),
               existing_nullable=False)
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.drop_index(op.f('ix_documentos_travel_id'), table_name='documentos')
    op.drop_column('documentos', 'travel_id')
    op.create_unique_constraint(op.f('briefings_lead_id_key'), 'briefings', ['lead_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('briefings', 'completude_pct',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('ix_aya_toggle_history_lead_id_alterado_em'), 'aya_toggle_history', ['lead_id', 'alterado_em'], unique=False)
    op.alter_column('agendamentos', 'tipo',
               existing_type=postgresql.ENUM('online', 'presencial', name='agendamento_tipo_enum'),
               server_default=sa.text("'online'::agendamento_tipo_enum"),
               existing_nullable=False)
    op.alter_column('agendamentos', 'status',
               existing_type=postgresql.ENUM('pendente', 'confirmado', 'realizado', 'cancelado', name='agendamento_status_enum'),
               server_default=sa.text("'pendente'::agendamento_status_enum"),
               existing_nullable=False)
    op.drop_index(op.f('ix_lead_score_history_lead_id'), table_name='lead_score_history')
    op.drop_table('lead_score_history')
    op.drop_index(op.f('ix_travels_user_id'), table_name='travels')
    op.drop_index(op.f('ix_travels_status'), table_name='travels')
    op.drop_table('travels')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
